version: '1'

services:
  backend:
    type: web
    name: laravel-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    build:
      context: ./backend
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=  # Update this if needed
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    type: database
    name: mysql-db
    image: mysql:8
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: todo_user
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    type: web
    name: react-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
