version: '1'

services:
  backend:
    name: laravel-backend
    type: web
    env: docker
    build:
      context: ./backend
      dockerfilePath: ./backend/Dockerfile  
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=  
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    name: mysql-db
    type: database
    image: mysql:8
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: todo_user
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  frontend:
    name: react-frontend
    type: web
    env: docker
    build:
      context: ./frontend
      dockerfilePath: ./frontend/Dockerfile 
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
